<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="bhas" failures="9" tests="17" name="Regression" time="11.123" errors="0" timestamp="2024-04-18T15:03:32 IST">
  <testcase classname="calculator.CalculatorTests" name="testNumberButtonsDisplay" time="0.65">
    <failure type="java.lang.AssertionError" message="expected [5] but found [6]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [6]
at calculator.CalculatorTests.testNumberButtonsDisplay(CalculatorTests.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testNumberButtonsDisplay -->
  <testcase classname="calculator.CalculatorTests" name="testcalculator_Add" time="0.31"/>
  <testcase classname="calculator.CalculatorTests" name="testcalculator_AddFloat" time="0.512">
    <failure type="java.lang.AssertionError" message="expected [99.8] but found [100.0]">
      <![CDATA[java.lang.AssertionError: expected [99.8] but found [100.0]
at calculator.CalculatorTests.testcalculator_AddFloat(CalculatorTests.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testcalculator_AddFloat -->
  <testcase classname="calculator.CalculatorTests" name="testcalculator_AddZero" time="0.292"/>
  <testcase classname="calculator.CalculatorTests" name="testcalculator_BigNumberTest" time="1.018"/>
  <testcase classname="calculator.CalculatorTests" name="testcalculator_FloatDivide" time="0.278">
    <failure type="java.lang.AssertionError" message="expected [4.5] but found [5.0]">
      <![CDATA[java.lang.AssertionError: expected [4.5] but found [5.0]
at calculator.CalculatorTests.testcalculator_FloatDivide(CalculatorTests.java:213)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testcalculator_FloatDivide -->
  <testcase classname="calculator.CalculatorTests" name="testcalculator_Integration1" time="0.339">
    <failure type="java.lang.AssertionError" message="expected [29] but found [32]">
      <![CDATA[java.lang.AssertionError: expected [29] but found [32]
at calculator.CalculatorTests.testcalculator_Integration1(CalculatorTests.java:244)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcalculator_Integration1 -->
  <testcase classname="calculator.CalculatorTests" name="testcalculator_Integration2Series" time="0.693">
    <failure type="java.lang.AssertionError" message="expected [98568] but found [98570]">
      <![CDATA[java.lang.AssertionError: expected [98568] but found [98570]
at calculator.CalculatorTests.testcalculator_Integration2Series(CalculatorTests.java:277)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcalculator_Integration2Series -->
  <testcase classname="calculator.CalculatorTests" name="testcalculator_Load" time="0.014"/>
  <testcase classname="calculator.CalculatorTests" name="testcalculator_Zeromultiply" time="0.273">
    <failure type="java.lang.AssertionError" message="expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [2]
at calculator.CalculatorTests.testcalculator_Zeromultiply(CalculatorTests.java:184)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcalculator_Zeromultiply -->
  <testcase classname="calculator.CalculatorTests" name="testcalculator_addMultiplyIntegration" time="0.498">
    <failure type="java.lang.AssertionError" message="expected [18] but found [20]">
      <![CDATA[java.lang.AssertionError: expected [18] but found [20]
at calculator.CalculatorTests.testcalculator_addMultiplyIntegration(CalculatorTests.java:226)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcalculator_addMultiplyIntegration -->
  <testcase classname="calculator.CalculatorTests" name="testcalculator_divide" time="0.291"/>
  <testcase classname="calculator.CalculatorTests" name="testcalculator_divideZero" time="0.27"/>
  <testcase classname="calculator.CalculatorTests" name="testcalculator_multiply" time="0.274">
    <failure type="java.lang.AssertionError" message="expected [24] but found [26]">
      <![CDATA[java.lang.AssertionError: expected [24] but found [26]
at calculator.CalculatorTests.testcalculator_multiply(CalculatorTests.java:175)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcalculator_multiply -->
  <testcase classname="calculator.CalculatorTests" name="testcalculator_subtract" time="0.283"/>
  <testcase classname="calculator.CalculatorTests" name="testcalculator_zerosubtractIntResult" time="0.268"/>
  <testcase classname="calculator.CalculatorTests" name="testcalculator_zerosubtractStringResult" time="0.267">
    <failure type="java.lang.AssertionError" message="expected [0] but found [-0]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [-0]
at calculator.CalculatorTests.testcalculator_zerosubtractStringResult(CalculatorTests.java:165)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcalculator_zerosubtractStringResult -->
</testsuite> <!-- Regression -->
