<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="bhas" failures="6" tests="11" name="Regression" time="8.648" errors="0" timestamp="2024-04-18T14:23:41 IST">
  <testcase classname="calculator.CalculatorTests" name="testNumberButtonsDisplay" time="0.565">
    <failure type="java.lang.AssertionError" message="expected [5] but found [6]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [6]
at calculator.CalculatorTests.testNumberButtonsDisplay(CalculatorTests.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testNumberButtonsDisplay -->
  <testcase classname="calculator.CalculatorTests" name="testcalculator_Add" time="0.287"/>
  <testcase classname="calculator.CalculatorTests" name="testcalculator_BigNumberTest" time="0.871"/>
  <testcase classname="calculator.CalculatorTests" name="testcalculator_FloatDivide" time="0.223">
    <failure type="java.lang.AssertionError" message="expected [4.5] but found [5.0]">
      <![CDATA[java.lang.AssertionError: expected [4.5] but found [5.0]
at calculator.CalculatorTests.testcalculator_FloatDivide(CalculatorTests.java:163)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testcalculator_FloatDivide -->
  <testcase classname="calculator.CalculatorTests" name="testcalculator_Integration1" time="0.285">
    <failure type="java.lang.AssertionError" message="expected [29] but found [32]">
      <![CDATA[java.lang.AssertionError: expected [29] but found [32]
at calculator.CalculatorTests.testcalculator_Integration1(CalculatorTests.java:194)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcalculator_Integration1 -->
  <testcase classname="calculator.CalculatorTests" name="testcalculator_Integration2Series" time="0.567">
    <failure type="java.lang.AssertionError" message="expected [98568] but found [98570]">
      <![CDATA[java.lang.AssertionError: expected [98568] but found [98570]
at calculator.CalculatorTests.testcalculator_Integration2Series(CalculatorTests.java:227)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcalculator_Integration2Series -->
  <testcase classname="calculator.CalculatorTests" name="testcalculator_Load" time="0.006"/>
  <testcase classname="calculator.CalculatorTests" name="testcalculator_addMultiplyIntegration" time="0.356">
    <failure type="java.lang.AssertionError" message="expected [18] but found [20]">
      <![CDATA[java.lang.AssertionError: expected [18] but found [20]
at calculator.CalculatorTests.testcalculator_addMultiplyIntegration(CalculatorTests.java:176)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcalculator_addMultiplyIntegration -->
  <testcase classname="calculator.CalculatorTests" name="testcalculator_divide" time="0.218"/>
  <testcase classname="calculator.CalculatorTests" name="testcalculator_multiply" time="0.2">
    <failure type="java.lang.AssertionError" message="expected [24] but found [26]">
      <![CDATA[java.lang.AssertionError: expected [24] but found [26]
at calculator.CalculatorTests.testcalculator_multiply(CalculatorTests.java:144)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcalculator_multiply -->
  <testcase classname="calculator.CalculatorTests" name="testcalculator_subtract" time="0.198"/>
</testsuite> <!-- Regression -->
